# src/formatter.py
from src.validator import PRDescription


def to_markdown(result: PRDescription, summary: dict) -> str:
    """
    Converts a validated PRDescription into a GitHub-ready Markdown string.
    
    This is what gets pasted into the GitHub PR description box.
    We follow GitHub's Markdown spec — headers with ##, bullets with -,
    horizontal rule with ---.
    
    Takes:
        result  — the validated Pydantic object from validator.py
        summary — the dict from get_diff_summary() in parser.py
                  contains total_files, total_added, total_removed etc.
    
    Returns:
        A single multiline string ready to copy-paste or pipe into gh CLI.
    """
    lines = []

    # ── Title ──────────────────────────────────────────────────────────
    # GitHub uses the first line of the PR description as a preview.
    # We put the title as a level-2 header so it's prominent.
    lines.append(f"## {result.title}")
    lines.append("")   # Blank line — Markdown needs this between sections

    # ── Summary ────────────────────────────────────────────────────────
    lines.append("### Summary")
    lines.append(result.summary)
    lines.append("")

    # ── Changes ────────────────────────────────────────────────────────
    # Only include this section if there are actual changes to list.
    # An empty "### Changes" section looks broken.
    if result.changes:
        lines.append("### Changes")
        for change in result.changes:
            # GitHub renders "- item" as a bullet point
            lines.append(f"- {change}")
        lines.append("")

    # ── Risks ──────────────────────────────────────────────────────────
    if result.risks:
        lines.append("### ⚠️ Risks / Review Notes")
        for risk in result.risks:
            lines.append(f"- {risk}")
        lines.append("")

    # ── Notes ──────────────────────────────────────────────────────────
    if result.notes and result.notes.strip():
        lines.append("### Notes")
        lines.append(result.notes)
        lines.append("")

    # ── Footer ─────────────────────────────────────────────────────────
    # A small automated footer so reviewers know this was AI-generated.
    # This is good practice — transparency about AI-assisted tooling.
    lines.append("---")
    lines.append(
        f"_Generated by git-pr-summarizer · "
        f"{summary['total_files']} file(s) changed · "
        f"+{summary['total_added']} / -{summary['total_removed']} lines_"
    )

    return "\n".join(lines)


def to_plain_text(result: PRDescription) -> str:
    """
    A plain text version — no Markdown symbols.
    Useful for terminals that don't render Markdown,
    or for piping into other tools.
    """
    lines = []
    lines.append(f"TITLE: {result.title}")
    lines.append(f"\nSUMMARY:\n{result.summary}")

    if result.changes:
        lines.append("\nCHANGES:")
        for change in result.changes:
            lines.append(f"  * {change}")

    if result.risks:
        lines.append("\nRISKS:")
        for risk in result.risks:
            lines.append(f"  ! {risk}")

    if result.notes and result.notes.strip():
        lines.append(f"\nNOTES:\n{result.notes}")

    return "\n".join(lines)


def to_github_body(result: PRDescription, summary: dict) -> str:
    """
    Identical to to_markdown() but with extra GitHub-specific formatting.
    Used specifically when piping into `gh pr create`.
    
    Adds a collapsible details section for the raw diff stats —
    GitHub renders <details> tags as expandable sections.
    """
    base = to_markdown(result, summary)

    # Append diff stats as a collapsible section
    stats_lines = [
        "",
        "<details>",
        "<summary>Diff stats</summary>",
        "",
        f"- Files changed: {summary['total_files']}",
        f"- Lines added: {summary['total_added']}",
        f"- Lines removed: {summary['total_removed']}",
    ]

    if summary.get("risky_files"):
        stats_lines.append(f"- Risky files: {', '.join(summary['risky_files'])}")

    if summary.get("extensions"):
        stats_lines.append(f"- Languages: {', '.join(summary['extensions'])}")

    stats_lines.append("")
    stats_lines.append("</details>")

    return base + "\n".join(stats_lines)